version: '3'

services:
  legal-entities-stats-app-container:
    image: legal-entities-stats:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /docker/legal-entities-stats
    ports:
      - "8080:8080"